///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UltraEditAutomation
{
    public partial class ASCIItoEBCDICConversion
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CheckAndClickYesButton(RepoItemInfo buttonYes)
        {
			try
			    {
				 // Check if the button exists within a specified timeout
				if (buttonYes.Exists(3000)) // Wait up to 3 seconds
			    {
				   // Create an adapter for the button and click it
				   var button = buttonYes.CreateAdapter<Button>(true);
			       button.Click();
				   Report.Info("The button was found and clicked.");
				}
				else
				{
			       Report.Info("The button does not exist. Continuing execution.");
			    }
			}
			catch (Exception ex)
			   {
			    // Log any unexpected errors but continue execution
			    Report.Error($"An error occurred while attempting to click the button: {ex.Message}");
			   }
		 }

    }
}
