///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CommentSpecificLine recording.
    /// </summary>
    [TestModule("dc03bf4b-bb16-4b68-90a0-08d8ad3b6d27", ModuleType.Recording, 1)]
    public partial class CommentSpecificLine : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UltraEditAutomationRepository repository.
        /// </summary>
        public static UltraEditAutomationRepository repo = UltraEditAutomationRepository.Instance;

        static CommentSpecificLine instance = new CommentSpecificLine();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CommentSpecificLine()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CommentSpecificLine Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'UltraEdit64Bit.ToolBar.Home'.", repo.UltraEdit64Bit.ToolBar.HomeInfo, new RecordItemIndex(0));
            repo.UltraEdit64Bit.ToolBar.Home.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Goto' at 20;24.", repo.UltraEdit64Bit.ToolBar.GotoInfo, new RecordItemIndex(1));
            repo.UltraEdit64Bit.ToolBar.Goto.Click("20;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.RadioButtonLineColumn' at 26;9.", repo.GoTo.RadioButtonLineColumnInfo, new RecordItemIndex(2));
            repo.GoTo.RadioButtonLineColumn.Click("26;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.Text1001' at 42;5.", repo.GoTo.Text1001Info, new RecordItemIndex(3));
            repo.GoTo.Text1001.Click("42;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'GoTo.Text1001'.", repo.GoTo.Text1001Info, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.GoTo.Text1001);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1/1' with focus on 'GoTo.Text1001'.", repo.GoTo.Text1001Info, new RecordItemIndex(5));
            repo.GoTo.Text1001.PressKeys("1/1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1/1') on item 'GoTo.Text1001'.", repo.GoTo.Text1001Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.GoTo.Text1001Info, "Text", "1/1");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.GoTo.Text1001, false, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'GoTo.Goto'.", repo.GoTo.GotoInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.GoTo.GotoInfo, "Enabled", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.Goto' at 56;8.", repo.GoTo.GotoInfo, new RecordItemIndex(9));
            repo.GoTo.Goto.Click("56;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'UltraEdit64Bit.ToolBar.Coding'.", repo.UltraEdit64Bit.ToolBar.CodingInfo, new RecordItemIndex(10));
            repo.UltraEdit64Bit.ToolBar.Coding.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.Comment' at 27;56.", repo.UltraEdit64Bit.CommentInfo, new RecordItemIndex(11));
            repo.UltraEdit64Bit.Comment.Click("27;56");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.AddLineComment' at 55;7.", repo.Uedit64.AddLineCommentInfo, new RecordItemIndex(12));
            repo.Uedit64.AddLineComment.Click("55;7");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.UltraEdit64Bit.editorScreen, false, new RecordItemIndex(13));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
