///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConvertTargetToUTF8 recording.
    /// </summary>
    [TestModule("0b042a5e-65f1-4ebd-a3de-8ff6d9de2b24", ModuleType.Recording, 1)]
    public partial class ConvertTargetToUTF8 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UltraEditAutomationRepository repository.
        /// </summary>
        public static UltraEditAutomationRepository repo = UltraEditAutomationRepository.Instance;

        static ConvertTargetToUTF8 instance = new ConvertTargetToUTF8();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConvertTargetToUTF8()
        {
            File = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConvertTargetToUTF8 Instance
        {
            get { return instance; }
        }

#region Variables

        string _File;

        /// <summary>
        /// Gets or sets the value of variable File.
        /// </summary>
        [TestVariable("45ca657e-91db-47cb-9f96-8c1e43a184c1")]
        public string File
        {
            get { return _File; }
            set { _File = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'FormCUltraEditFilesUe20241025T06120.Edit'.", repo.FormCUltraEditFilesUe20241025T06120.EditInfo, new RecordItemIndex(0));
            repo.FormCUltraEditFilesUe20241025T06120.Edit.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Select' at 21;57.", repo.FormCUltraEditFilesUe20241025T06120.SelectInfo, new RecordItemIndex(1));
            repo.FormCUltraEditFilesUe20241025T06120.Select.Click("21;57");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.SelectWord' at 75;11.", repo.Uedit64.SelectWordInfo, new RecordItemIndex(2));
            repo.Uedit64.SelectWord.Click("75;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.Home' at 38;14.", repo.UltraEdit64Bit.HomeInfo, new RecordItemIndex(3));
            repo.UltraEdit64Bit.Home.Click("38;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Copy' at 57;13.", repo.FormCUltraEditFilesUe20241025T06120.CopyInfo, new RecordItemIndex(4));
            repo.FormCUltraEditFilesUe20241025T06120.Copy.Click("57;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Copy' at 53;13.", repo.Uedit64.CopyInfo, new RecordItemIndex(5));
            repo.Uedit64.Copy.Click("53;13");
            Delay.Milliseconds(0);
            
            PrintCopiedText();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.ButtonNew' at 8;10.", repo.Uedit64.ButtonNewInfo, new RecordItemIndex(7));
            repo.Uedit64.ButtonNew.Click("8;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Paste' at 22;57.", repo.Uedit64.PasteInfo, new RecordItemIndex(8));
            repo.Uedit64.Paste.Click("22;57");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Paste1' at 40;11.", repo.Uedit64.Paste1Info, new RecordItemIndex(9));
            repo.Uedit64.Paste1.Click("40;11");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Uedit64.BeforeWePasteThisData, false, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.EncryptButtonYes' at 26;12.", repo.Uedit64.EncryptButtonYesInfo, new RecordItemIndex(11));
            repo.Uedit64.EncryptButtonYes.Click("26;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.SaveButton' at 10;9.", repo.Uedit64.SaveButtonInfo, new RecordItemIndex(12));
            repo.Uedit64.SaveButton.Click("10;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$File' with focus on 'SaveAs.Text1001'.", repo.SaveAs.Text1001Info, new RecordItemIndex(13));
            repo.SaveAs.Text1001.PressKeys(File);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at 22;17.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(14));
            repo.SaveAs.ButtonSave.Click("22;17");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
