///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PasteFullLineContent recording.
    /// </summary>
    [TestModule("080266c3-b53a-40a5-89b1-7bc05f4d283f", ModuleType.Recording, 1)]
    public partial class PasteFullLineContent : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UltraEditAutomationRepository repository.
        /// </summary>
        public static UltraEditAutomationRepository repo = UltraEditAutomationRepository.Instance;

        static PasteFullLineContent instance = new PasteFullLineContent();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PasteFullLineContent()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PasteFullLineContent Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Home' at 35;13.", repo.UltraEdit64Bit.ToolBar.HomeInfo, new RecordItemIndex(0));
            repo.UltraEdit64Bit.ToolBar.Home.Click("35;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Goto' at 24;14.", repo.UltraEdit64Bit.ToolBar.GotoInfo, new RecordItemIndex(1));
            repo.UltraEdit64Bit.ToolBar.Goto.Click("24;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.RadioButtonLineColumn' at 48;10.", repo.GoTo.RadioButtonLineColumnInfo, new RecordItemIndex(2));
            repo.GoTo.RadioButtonLineColumn.Click("48;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '8/1' with focus on 'GoTo'.", repo.GoTo.SelfInfo, new RecordItemIndex(3));
            repo.GoTo.Self.EnsureVisible();
            Keyboard.Press("8/1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.Goto' at 26;12.", repo.GoTo.GotoInfo, new RecordItemIndex(4));
            repo.GoTo.Goto.Click("26;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Edit' at 30;14.", repo.FormCUltraEditFilesUe20241025T06120.EditInfo, new RecordItemIndex(5));
            repo.FormCUltraEditFilesUe20241025T06120.Edit.Click("30;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Select' at 20;54.", repo.FormCUltraEditFilesUe20241025T06120.SelectInfo, new RecordItemIndex(6));
            repo.FormCUltraEditFilesUe20241025T06120.Select.Click("20;54");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.SelectLine' at 71;10.", repo.Uedit64.SelectLineInfo, new RecordItemIndex(7));
            repo.Uedit64.SelectLine.Click("71;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'UltraEdit64Bit.ToolBar.Home'.", repo.UltraEdit64Bit.ToolBar.HomeInfo, new RecordItemIndex(8));
            repo.UltraEdit64Bit.ToolBar.Home.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Copy' at 57;12.", repo.FormCUltraEditFilesUe20241025T06120.CopyInfo, new RecordItemIndex(9));
            repo.FormCUltraEditFilesUe20241025T06120.Copy.Click("57;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Copy' at 62;14.", repo.Uedit64.CopyInfo, new RecordItemIndex(10));
            repo.Uedit64.Copy.Click("62;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{End down}{LControlKey up}{End up}' with focus on 'FormCUltraEditFilesUe20241025T06120'.", repo.FormCUltraEditFilesUe20241025T06120.SelfInfo, new RecordItemIndex(11));
            repo.FormCUltraEditFilesUe20241025T06120.Self.EnsureVisible();
            Keyboard.Press("{LControlKey down}{End down}{LControlKey up}{End up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.ToolBar.Paste' at 23;55.", repo.FormCUltraEditFilesUe20241025T06120.ToolBar.PasteInfo, new RecordItemIndex(12));
            repo.FormCUltraEditFilesUe20241025T06120.ToolBar.Paste.Click("23;55");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Paste1' at 77;15.", repo.Uedit64.Paste1Info, new RecordItemIndex(13));
            repo.Uedit64.Paste1.Click("77;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
