///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PerformSearchCriteria recording.
    /// </summary>
    [TestModule("11ed9aa5-4ddf-4d81-9451-3977c3bdb6e3", ModuleType.Recording, 1)]
    public partial class PerformSearchCriteria : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UltraEditAutomationRepository repository.
        /// </summary>
        public static UltraEditAutomationRepository repo = UltraEditAutomationRepository.Instance;

        static PerformSearchCriteria instance = new PerformSearchCriteria();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PerformSearchCriteria()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PerformSearchCriteria Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.FindTextField' at Center.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(0));
            repo.FindAndReplace.Uedit64.FindTextField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'test' with focus on 'FindAndReplace.Uedit64.FindTextField'.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(1));
            repo.FindAndReplace.Uedit64.FindTextField.PressKeys("test");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'FindAndReplace.Uedit64.FilesListed'.", repo.FindAndReplace.Uedit64.FilesListedInfo, new RecordItemIndex(2));
            repo.FindAndReplace.Uedit64.FilesListed.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'FindAndReplace.Uedit64.FilesListed'.", repo.FindAndReplace.Uedit64.FilesListedInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.FilesListedInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.FileType' at Center.", repo.FindAndReplace.Uedit64.FileTypeInfo, new RecordItemIndex(4));
            repo.FindAndReplace.Uedit64.FileType.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '*.txt' with focus on 'FindAndReplace.Uedit64.FileType'.", repo.FindAndReplace.Uedit64.FileTypeInfo, new RecordItemIndex(5));
            repo.FindAndReplace.Uedit64.FileType.PressKeys("*.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.DirectoryPath' at Center.", repo.FindAndReplace.Uedit64.DirectoryPathInfo, new RecordItemIndex(6));
            repo.FindAndReplace.Uedit64.DirectoryPath.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'C:\\UltraEditFiles\\ue-20241025T061201Z-004\\ue\\encodingTestsBOM' with focus on 'FindAndReplace.Uedit64.DirectoryPath'.", repo.FindAndReplace.Uedit64.DirectoryPathInfo, new RecordItemIndex(7));
            repo.FindAndReplace.Uedit64.DirectoryPath.PressKeys("C:\\UltraEditFiles\\ue-20241025T061201Z-004\\ue\\encodingTestsBOM");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.GearButton' at Center.", repo.FindAndReplace.Uedit64.GearButtonInfo, new RecordItemIndex(8));
            repo.FindAndReplace.Uedit64.GearButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'FindAndReplace.Uedit64.SearchSubdirectories'.", repo.FindAndReplace.Uedit64.SearchSubdirectoriesInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.SearchSubdirectoriesInfo, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Find' at Center.", repo.FindAndReplace.Uedit64.FindInfo, new RecordItemIndex(10));
            repo.FindAndReplace.Uedit64.Find.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
