///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateMatchStringCount recording.
    /// </summary>
    [TestModule("69850bed-bb16-49e1-b33e-174fea4c5691", ModuleType.Recording, 1)]
    public partial class ValidateMatchStringCount : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UltraEditAutomationRepository repository.
        /// </summary>
        public static UltraEditAutomationRepository repo = UltraEditAutomationRepository.Instance;

        static ValidateMatchStringCount instance = new ValidateMatchStringCount();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateMatchStringCount()
        {
            Text = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateMatchStringCount Instance
        {
            get { return instance; }
        }

#region Variables

        string _Text;

        /// <summary>
        /// Gets or sets the value of variable Text.
        /// </summary>
        [TestVariable("daea8584-7f20-4448-98ee-657ea3c9e69c")]
        public string Text
        {
            get { return _Text; }
            set { _Text = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.GearButton' at 16;11.", repo.FindAndReplace.Uedit64.GearButtonInfo, new RecordItemIndex(0));
            repo.FindAndReplace.Uedit64.GearButton.Click("16;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.CheckBoxCloseAfterFind' at 10;3.", repo.FindAndReplace.Uedit64.CheckBoxCloseAfterFindInfo, new RecordItemIndex(1));
            repo.FindAndReplace.Uedit64.CheckBoxCloseAfterFind.Click("10;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='False') on item 'FindAndReplace.Uedit64.CheckBoxCloseAfterFind'.", repo.FindAndReplace.Uedit64.CheckBoxCloseAfterFindInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.CheckBoxCloseAfterFindInfo, "Checked", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.FindTextField' at 75;13.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(3));
            repo.FindAndReplace.Uedit64.FindTextField.Click("75;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'FindAndReplace.Uedit64.FindTextField'.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.FindAndReplace.Uedit64.FindTextField);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Text' with focus on 'FindAndReplace.Uedit64.FindTextField'.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(5));
            repo.FindAndReplace.Uedit64.FindTextField.PressKeys(Text);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.ButtonNext' at 31;10.", repo.FindAndReplace.Uedit64.ButtonNextInfo, new RecordItemIndex(6));
            repo.FindAndReplace.Uedit64.ButtonNext.Click("31;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.CountAll' at 53;11.", repo.FindAndReplace.Uedit64.CountAllInfo, new RecordItemIndex(7));
            repo.FindAndReplace.Uedit64.CountAll.Click("53;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='19 occurrences found.') on item 'FindAndReplace.Uedit64.occurrences'.", repo.FindAndReplace.Uedit64.occurrencesInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.occurrencesInfo, "Text", "19 occurrences found.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Close() on item 'FindAndReplace'.", repo.FindAndReplace.SelfInfo, new RecordItemIndex(9));
            repo.FindAndReplace.Self.Close();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
