///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidatingQuickFindDialogPosition recording.
    /// </summary>
    [TestModule("599e747d-5423-4b6d-abef-ac8a1f3576fd", ModuleType.Recording, 1)]
    public partial class ValidatingQuickFindDialogPosition : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UltraEditAutomationRepository repository.
        /// </summary>
        public static UltraEditAutomationRepository repo = UltraEditAutomationRepository.Instance;

        static ValidatingQuickFindDialogPosition instance = new ValidatingQuickFindDialogPosition();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidatingQuickFindDialogPosition()
        {
            tolerance = "20";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidatingQuickFindDialogPosition Instance
        {
            get { return instance; }
        }

#region Variables

        string _tolerance;

        /// <summary>
        /// Gets or sets the value of variable tolerance.
        /// </summary>
        [TestVariable("8424cf30-149e-4a04-ad9b-3ac7b7bc7265")]
        public string tolerance
        {
            get { return _tolerance; }
            set { _tolerance = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            ValidatePosition(repo.Uedit64.EditWindow, repo.Uedit64.QuickFind, ValueConverter.ArgumentFromString<int>("tolerance", tolerance));
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.Uedit64.EditWindow, false, new RecordItemIndex(1));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
