///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UltraEditAutomation
{
    public partial class VerifyFile_inMultipleLine
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void VerifyTextIsInMultipleLines()
        {
            try
    {
        var editorScreen = repo.UltraEdit64Bit.editorScreen;

        if (editorScreen == null)
        {
            Report.Error("Editor Screen element not found.");
            return;
        }

        // Retrieve the full text from the "WindowText" attribute
        string fullText = editorScreen.Element.GetAttributeValueText("WindowText");

        // Report the full text without splitting by lines
        Report.Info("Full Text Retrieved: ");
        Report.Info(fullText); // This will print the full text without splitting

        // If needed, count the number of characters instead of lines
        int textLength = fullText.Length;
        Report.Info($"Text Length: {textLength} characters");
    }
            
        catch (Exception ex) {
            	
            	Report.Error($"An error occurred while verifying the text: {ex.Message}");
            }
        }

    }
}
