///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyCloseTag recording.
    /// </summary>
    [TestModule("65cbedfa-0485-4e10-944e-ec709981d248", ModuleType.Recording, 1)]
    public partial class VerifyCloseTag : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UltraEditAutomationRepository repository.
        /// </summary>
        public static UltraEditAutomationRepository repo = UltraEditAutomationRepository.Instance;

        static VerifyCloseTag instance = new VerifyCloseTag();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyCloseTag()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyCloseTag Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Home' at 26;19.", repo.UltraEdit64Bit.ToolBar.HomeInfo, new RecordItemIndex(0));
            repo.UltraEdit64Bit.ToolBar.Home.Click("26;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Goto' at 20;28.", repo.UltraEdit64Bit.ToolBar.GotoInfo, new RecordItemIndex(1));
            repo.UltraEdit64Bit.ToolBar.Goto.Click("20;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.RadioButtonLineColumn' at 70;11.", repo.GoTo.RadioButtonLineColumnInfo, new RecordItemIndex(2));
            repo.GoTo.RadioButtonLineColumn.Click("70;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2/1' with focus on 'GoTo'.", repo.GoTo.SelfInfo, new RecordItemIndex(3));
            repo.GoTo.Self.EnsureVisible();
            Keyboard.Press("2/1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.Goto' at 51;13.", repo.GoTo.GotoInfo, new RecordItemIndex(4));
            repo.GoTo.Goto.Click("51;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}{, down}{RShiftKey up}junk{RShiftKey down}>{RShiftKey up}' with focus on 'FormCUltraEditFilesUe20241025T06120'.", repo.FormCUltraEditFilesUe20241025T06120.SelfInfo, new RecordItemIndex(5));
            repo.FormCUltraEditFilesUe20241025T06120.Self.EnsureVisible();
            Keyboard.Press("{RShiftKey down}{, down}{RShiftKey up}junk{RShiftKey down}>{RShiftKey up}");
            Delay.Milliseconds(0);
            
            ApeearenceofTag();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
