///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyHistoryBeforeChangingSettings recording.
    /// </summary>
    [TestModule("dc6151b8-f755-4c33-af46-dcc38882c83b", ModuleType.Recording, 1)]
    public partial class VerifyHistoryBeforeChangingSettings : ITestModule
    {
        /// <summary>
        /// Holds an instance of the UltraEditAutomationRepository repository.
        /// </summary>
        public static UltraEditAutomationRepository repo = UltraEditAutomationRepository.Instance;

        static VerifyHistoryBeforeChangingSettings instance = new VerifyHistoryBeforeChangingSettings();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyHistoryBeforeChangingSettings()
        {
            Text = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyHistoryBeforeChangingSettings Instance
        {
            get { return instance; }
        }

#region Variables

        string _Text;

        /// <summary>
        /// Gets or sets the value of variable Text.
        /// </summary>
        [TestVariable("e6aff21f-71d9-4393-9848-a21784242326")]
        public string Text
        {
            get { return _Text; }
            set { _Text = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'FormEdit1UltraEdit64Bit.Edit1'.", repo.FormEdit1UltraEdit64Bit.Edit1Info, new RecordItemIndex(0));
            repo.FormEdit1UltraEdit64Bit.Edit1.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.Home' at 26;8.", repo.UltraEdit64Bit.HomeInfo, new RecordItemIndex(1));
            repo.UltraEdit64Bit.Home.Click("26;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormEdit1UltraEdit64Bit.Find' at 20;55.", repo.FormEdit1UltraEdit64Bit.FindInfo, new RecordItemIndex(2));
            repo.FormEdit1UltraEdit64Bit.Find.Click("20;55");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FindAndReplace'.", repo.FindAndReplace.SelfInfo, new RecordItemIndex(3));
            Validate.Exists(repo.FindAndReplace.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'FindAndReplace.Find'.", repo.FindAndReplace.FindInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.FindAndReplace.FindInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            // Find Tab
            Report.Log(ReportLevel.Info, "Section", "Find Tab", new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.FindTextField' at 27;18.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(6));
            repo.FindAndReplace.Uedit64.FindTextField.Click("27;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Text' with focus on 'FindAndReplace.Uedit64.FindTextField'.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(7));
            repo.FindAndReplace.Uedit64.FindTextField.PressKeys(Text);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.ButtonNext' at 55;12.", repo.FindAndReplace.Uedit64.ButtonNextInfo, new RecordItemIndex(8));
            repo.FindAndReplace.Uedit64.ButtonNext.Click("55;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit.ButtonOK' at 20;9.", repo.UltraEdit.ButtonOKInfo, new RecordItemIndex(9));
            repo.UltraEdit.ButtonOK.Click("20;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Button' at 15;14.", repo.FindAndReplace.Uedit64.ButtonInfo, new RecordItemIndex(10));
            repo.FindAndReplace.Uedit64.Button.Click("15;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Uedit64.abcd'.", repo.Uedit64.abcdInfo, new RecordItemIndex(11));
            Validate.Exists(repo.Uedit64.abcdInfo);
            Delay.Milliseconds(0);
            
            // ReplaceTab
            Report.Log(ReportLevel.Info, "Section", "ReplaceTab", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Replace' at 20;8.", repo.FindAndReplace.ReplaceInfo, new RecordItemIndex(13));
            repo.FindAndReplace.Replace.Click("20;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Button' at 7;16.", repo.FindAndReplace.Uedit64.ButtonInfo, new RecordItemIndex(14));
            repo.FindAndReplace.Uedit64.Button.Click("7;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Uedit64.abcd'.", repo.Uedit64.abcdInfo, new RecordItemIndex(15));
            Validate.Exists(repo.Uedit64.abcdInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.ReplaceTextField' at 69;16.", repo.FindAndReplace.Uedit64.ReplaceTextFieldInfo, new RecordItemIndex(16));
            repo.FindAndReplace.Uedit64.ReplaceTextField.Click("69;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Text' with focus on 'FindAndReplace.Uedit64.ReplaceTextField'.", repo.FindAndReplace.Uedit64.ReplaceTextFieldInfo, new RecordItemIndex(17));
            repo.FindAndReplace.Uedit64.ReplaceTextField.PressKeys(Text);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.ButtonNext' at 19;8.", repo.FindAndReplace.Uedit64.ButtonNextInfo, new RecordItemIndex(18));
            repo.FindAndReplace.Uedit64.ButtonNext.Click("19;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit.ButtonOK' at 44;10.", repo.UltraEdit.ButtonOKInfo, new RecordItemIndex(19));
            repo.UltraEdit.ButtonOK.Click("44;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Button1' at 10;18.", repo.FindAndReplace.Uedit64.Button1Info, new RecordItemIndex(20));
            repo.FindAndReplace.Uedit64.Button1.Click("10;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Uedit64.abcd'.", repo.Uedit64.abcdInfo, new RecordItemIndex(21));
            Validate.Exists(repo.Uedit64.abcdInfo);
            Delay.Milliseconds(0);
            
            // FindInFiles
            Report.Log(ReportLevel.Info, "Section", "FindInFiles", new RecordItemIndex(22));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.FindInFiles' at 55;8.", repo.FindAndReplace.FindInFilesInfo, new RecordItemIndex(23));
            repo.FindAndReplace.FindInFiles.Click("55;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Button' at 19;13.", repo.FindAndReplace.Uedit64.ButtonInfo, new RecordItemIndex(24));
            repo.FindAndReplace.Uedit64.Button.Click("19;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Uedit64.abcd'.", repo.Uedit64.abcdInfo, new RecordItemIndex(25));
            Validate.Exists(repo.Uedit64.abcdInfo);
            Delay.Milliseconds(0);
            
            // ReplaceInFiles
            Report.Log(ReportLevel.Info, "Section", "ReplaceInFiles", new RecordItemIndex(26));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.ReplaceInFiles' at 66;3.", repo.FindAndReplace.ReplaceInFilesInfo, new RecordItemIndex(27));
            repo.FindAndReplace.ReplaceInFiles.Click("66;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Button' at 7;6.", repo.FindAndReplace.Uedit64.ButtonInfo, new RecordItemIndex(28));
            repo.FindAndReplace.Uedit64.Button.Click("7;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Uedit64.abcd'.", repo.Uedit64.abcdInfo, new RecordItemIndex(29));
            Validate.Exists(repo.Uedit64.abcdInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'FindAndReplace.Uedit64.Button1'.", repo.FindAndReplace.Uedit64.Button1Info, new RecordItemIndex(30));
            repo.FindAndReplace.Uedit64.Button1.Press();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Middle Click item 'FindAndReplace.Uedit64.Button1' at 11;16.", repo.FindAndReplace.Uedit64.Button1Info, new RecordItemIndex(31));
            //repo.FindAndReplace.Uedit64.Button1.Click(System.Windows.Forms.MouseButtons.Middle, "11;16");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Uedit64.abcd'.", repo.Uedit64.abcdInfo, new RecordItemIndex(32));
            Validate.Exists(repo.Uedit64.abcdInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Close() on item 'FindAndReplace'.", repo.FindAndReplace.SelfInfo, new RecordItemIndex(33));
            repo.FindAndReplace.Self.Close();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
