///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.SearchTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchCriteriaForEditWindow recording.
    /// </summary>
    [TestModule("85b28673-7b93-435c-b571-826a70cf5480", ModuleType.Recording, 1)]
    public partial class SearchCriteriaForEditWindow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static SearchCriteriaForEditWindow instance = new SearchCriteriaForEditWindow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchCriteriaForEditWindow()
        {
            Text = "";
            DirectoryPath = "C:\\UltraEditFiles\\ue-20241025T061201Z-004\\ue\\encodingTestsBOM";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchCriteriaForEditWindow Instance
        {
            get { return instance; }
        }

#region Variables

        string _Text;

        /// <summary>
        /// Gets or sets the value of variable Text.
        /// </summary>
        [TestVariable("46c5a57d-5a73-4ab8-9dd4-f4cedf3e348f")]
        public string Text
        {
            get { return _Text; }
            set { _Text = value; }
        }

        string _DirectoryPath;

        /// <summary>
        /// Gets or sets the value of variable DirectoryPath.
        /// </summary>
        [TestVariable("3b5459a7-b50f-453e-ab4e-49d5fb581368")]
        public string DirectoryPath
        {
            get { return _DirectoryPath; }
            set { _DirectoryPath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.FindTextField' at Center.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(0));
            repo.FindAndReplace.Uedit64.FindTextField.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Text' with focus on 'FindAndReplace.Uedit64.FindTextField'.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(1));
            repo.FindAndReplace.Uedit64.FindTextField.PressKeys(Text);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'FindAndReplace.Uedit64.FilesListed'.", repo.FindAndReplace.Uedit64.FilesListedInfo, new RecordItemIndex(2));
            repo.FindAndReplace.Uedit64.FilesListed.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'FindAndReplace.Uedit64.FilesListed'.", repo.FindAndReplace.Uedit64.FilesListedInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.FilesListedInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.DirectoryPath' at Center.", repo.FindAndReplace.Uedit64.DirectoryPathInfo, new RecordItemIndex(4));
            repo.FindAndReplace.Uedit64.DirectoryPath.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DirectoryPath' with focus on 'FindAndReplace.Uedit64.DirectoryPath'.", repo.FindAndReplace.Uedit64.DirectoryPathInfo, new RecordItemIndex(5));
            repo.FindAndReplace.Uedit64.DirectoryPath.PressKeys(DirectoryPath);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.GearButton' at Center.", repo.FindAndReplace.Uedit64.GearButtonInfo, new RecordItemIndex(6));
            repo.FindAndReplace.Uedit64.GearButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Check() on item 'FindAndReplace.Uedit64.ResultsToEditWindow'.", repo.FindAndReplace.Uedit64.ResultsToEditWindowInfo, new RecordItemIndex(7));
            repo.FindAndReplace.Uedit64.ResultsToEditWindow.Check();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'FindAndReplace.Uedit64.ResultsToEditWindow'.", repo.FindAndReplace.Uedit64.ResultsToEditWindowInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.ResultsToEditWindowInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Check() on item 'FindAndReplace.Uedit64.SearchSubdirectories'.", repo.FindAndReplace.Uedit64.SearchSubdirectoriesInfo, new RecordItemIndex(9));
            repo.FindAndReplace.Uedit64.SearchSubdirectories.Check();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'FindAndReplace.Uedit64.SearchSubdirectories'.", repo.FindAndReplace.Uedit64.SearchSubdirectoriesInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.SearchSubdirectoriesInfo, "Checked", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Find' at Center.", repo.FindAndReplace.Uedit64.FindInfo, new RecordItemIndex(11));
            repo.FindAndReplace.Uedit64.Find.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
