///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.SearchTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchCriteriaForStringNotFoundInFiles recording.
    /// </summary>
    [TestModule("df8813d7-4ecf-4cf3-b72d-6e66074d3dbb", ModuleType.Recording, 1)]
    public partial class SearchCriteriaForStringNotFoundInFiles : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static SearchCriteriaForStringNotFoundInFiles instance = new SearchCriteriaForStringNotFoundInFiles();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchCriteriaForStringNotFoundInFiles()
        {
            Text = "";
            FileType = "";
            Path = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchCriteriaForStringNotFoundInFiles Instance
        {
            get { return instance; }
        }

#region Variables

        string _Text;

        /// <summary>
        /// Gets or sets the value of variable Text.
        /// </summary>
        [TestVariable("b7d3bf1c-c7ec-46ad-b412-184625225eef")]
        public string Text
        {
            get { return _Text; }
            set { _Text = value; }
        }

        string _FileType;

        /// <summary>
        /// Gets or sets the value of variable FileType.
        /// </summary>
        [TestVariable("fcefc90c-3376-47e5-95a1-c0abec40b04d")]
        public string FileType
        {
            get { return _FileType; }
            set { _FileType = value; }
        }

        string _Path;

        /// <summary>
        /// Gets or sets the value of variable Path.
        /// </summary>
        [TestVariable("d5e9b6c6-7f13-4c05-8ac8-a87e4c4855ff")]
        public string Path
        {
            get { return _Path; }
            set { _Path = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Text' with focus on 'FindAndReplace.Uedit64.FindTextField'.", repo.FindAndReplace.Uedit64.FindTextFieldInfo, new RecordItemIndex(0));
            repo.FindAndReplace.Uedit64.FindTextField.PressKeys(Text);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'FindAndReplace.Uedit64.FilesListed'.", repo.FindAndReplace.Uedit64.FilesListedInfo, new RecordItemIndex(1));
            repo.FindAndReplace.Uedit64.FilesListed.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'FindAndReplace.Uedit64.FilesListed'.", repo.FindAndReplace.Uedit64.FilesListedInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.FilesListedInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FileType' with focus on 'FindAndReplace.Uedit64.FileType'.", repo.FindAndReplace.Uedit64.FileTypeInfo, new RecordItemIndex(3));
            repo.FindAndReplace.Uedit64.FileType.PressKeys(FileType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$FileType) on item 'FindAndReplace.Uedit64.FileType'.", repo.FindAndReplace.Uedit64.FileTypeInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.FileTypeInfo, "Text", FileType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Path' with focus on 'FindAndReplace.Uedit64.DirectoryPath'.", repo.FindAndReplace.Uedit64.DirectoryPathInfo, new RecordItemIndex(5));
            repo.FindAndReplace.Uedit64.DirectoryPath.PressKeys(Path);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.GearButton' at Center.", repo.FindAndReplace.Uedit64.GearButtonInfo, new RecordItemIndex(6));
            repo.FindAndReplace.Uedit64.GearButton.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Match' at Center.", repo.FindAndReplace.Uedit64.MatchInfo, new RecordItemIndex(7));
            repo.FindAndReplace.Uedit64.Match.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'FindAndReplace.Uedit64.Match'.", repo.FindAndReplace.Uedit64.MatchInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.MatchInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Files' at Center.", repo.FindAndReplace.Uedit64.FilesInfo, new RecordItemIndex(9));
            repo.FindAndReplace.Uedit64.Files.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'FindAndReplace.Uedit64.Files'.", repo.FindAndReplace.Uedit64.FilesInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.FindAndReplace.Uedit64.FilesInfo, "Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FindAndReplace.Uedit64.Find' at Center.", repo.FindAndReplace.Uedit64.FindInfo, new RecordItemIndex(11));
            repo.FindAndReplace.Uedit64.Find.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
