///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.Editing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The comparetext recording.
    /// </summary>
    [TestModule("f7391458-ddea-4db5-a9e2-44ac69e0ad3b", ModuleType.Recording, 1)]
    public partial class comparetext : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static comparetext instance = new comparetext();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public comparetext()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static comparetext Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.ClearClipboardJs' at 78;11.", repo.FormCUltraEditFilesUe20241025T06120.ClearClipboardJsInfo, new RecordItemIndex(0));
            repo.FormCUltraEditFilesUe20241025T06120.ClearClipboardJs.Click("78;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Home' at 30;10.", repo.UltraEdit64Bit.ToolBar.HomeInfo, new RecordItemIndex(1));
            repo.UltraEdit64Bit.ToolBar.Home.Click("30;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Goto' at 19;25.", repo.UltraEdit64Bit.ToolBar.GotoInfo, new RecordItemIndex(2));
            repo.UltraEdit64Bit.ToolBar.Goto.Click("19;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.RadioButtonLineColumn' at 31;12.", repo.GoTo.RadioButtonLineColumnInfo, new RecordItemIndex(3));
            repo.GoTo.RadioButtonLineColumn.Click("31;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '14/1' with focus on 'GoTo'.", repo.GoTo.SelfInfo, new RecordItemIndex(4));
            repo.GoTo.Self.EnsureVisible();
            Keyboard.Press("14/1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.Goto' at 38;14.", repo.GoTo.GotoInfo, new RecordItemIndex(5));
            repo.GoTo.Goto.Click("38;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Goto' at 15;21.", repo.UltraEdit64Bit.ToolBar.GotoInfo, new RecordItemIndex(6));
            repo.UltraEdit64Bit.ToolBar.Goto.Click("15;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.RadioButtonLineColumn' at 54;13.", repo.GoTo.RadioButtonLineColumnInfo, new RecordItemIndex(7));
            repo.GoTo.RadioButtonLineColumn.Click("54;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '21/2' with focus on 'GoTo'.", repo.GoTo.SelfInfo, new RecordItemIndex(8));
            repo.GoTo.Self.EnsureVisible();
            Keyboard.Press("21/2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}' with focus on 'GoTo'.", repo.GoTo.SelfInfo, new RecordItemIndex(9));
            repo.GoTo.Self.EnsureVisible();
            Keyboard.Press("{LShiftKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.Goto' at 40;15.", repo.GoTo.GotoInfo, new RecordItemIndex(10));
            repo.GoTo.Goto.Click("40;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey up}' with focus on 'UltraEdit64Bit.editorScreen'.", repo.UltraEdit64Bit.editorScreenInfo, new RecordItemIndex(11));
            repo.UltraEdit64Bit.editorScreen.EnsureVisible();
            Keyboard.Press("{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(12));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+C' Press with focus on 'FormCUltraEditFilesUe20241025T06120'.", repo.FormCUltraEditFilesUe20241025T06120.SelfInfo, new RecordItemIndex(13));
            Keyboard.PrepareFocus(repo.FormCUltraEditFilesUe20241025T06120.Self);
            Keyboard.Press(System.Windows.Forms.Keys.C | System.Windows.Forms.Keys.Control, 46, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Content1();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.JSfragmentHtml' at 65;12.", repo.FormCUltraEditFilesUe20241025T06120.JSfragmentHtmlInfo, new RecordItemIndex(15));
            repo.FormCUltraEditFilesUe20241025T06120.JSfragmentHtml.Click("65;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.ShowInDefaultApp' at 29;24.", repo.FormCUltraEditFilesUe20241025T06120.ShowInDefaultAppInfo, new RecordItemIndex(16));
            repo.FormCUltraEditFilesUe20241025T06120.ShowInDefaultApp.Click("29;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'MicrosoftEdge'.", repo.MicrosoftEdge.SelfInfo, new RecordItemIndex(17));
            Keyboard.PrepareFocus(repo.MicrosoftEdge.Self);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+C' Press with focus on 'MicrosoftEdge'.", repo.MicrosoftEdge.SelfInfo, new RecordItemIndex(18));
            Keyboard.PrepareFocus(repo.MicrosoftEdge.Self);
            Keyboard.Press(System.Windows.Forms.Keys.C | System.Windows.Forms.Keys.Control, 46, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Content2();
            Delay.Milliseconds(0);
            
            CompareContent();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'MicrosoftEdge'", repo.MicrosoftEdge.SelfInfo, new ActionTimeout(5000), new RecordItemIndex(21));
            repo.MicrosoftEdge.SelfInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'MicrosoftEdge'.", repo.MicrosoftEdge.SelfInfo, new RecordItemIndex(22));
            Host.Current.CloseApplication(repo.MicrosoftEdge.Self, new Duration(0));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(23));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
