///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.Editing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteToEnd recording.
    /// </summary>
    [TestModule("f2280f39-fd10-4608-81ba-9d233103227a", ModuleType.Recording, 1)]
    public partial class DeleteToEnd : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static DeleteToEnd instance = new DeleteToEnd();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteToEnd()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteToEnd Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            retriveTextofLine();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'UltraEdit64Bit.Home'.", repo.UltraEdit64Bit.HomeInfo, new RecordItemIndex(1));
            repo.UltraEdit64Bit.Home.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Goto' at 23;23.", repo.Uedit64.GotoInfo, new RecordItemIndex(2));
            repo.Uedit64.Goto.Click("23;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.RadioButtonLineColumn' at 23;12.", repo.GoTo.RadioButtonLineColumnInfo, new RecordItemIndex(3));
            repo.GoTo.RadioButtonLineColumn.Click("23;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '8/33' with focus on 'GoTo'.", repo.GoTo.SelfInfo, new RecordItemIndex(4));
            repo.GoTo.Self.EnsureVisible();
            Keyboard.Press("8/33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.Goto' at 60;17.", repo.GoTo.GotoInfo, new RecordItemIndex(5));
            repo.GoTo.Goto.Click("60;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'Uedit64.Edit'.", repo.Uedit64.EditInfo, new RecordItemIndex(6));
            repo.Uedit64.Edit.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Delete' at 21;56.", repo.Uedit64.DeleteInfo, new RecordItemIndex(7));
            repo.Uedit64.Delete.Click("21;56");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.DeleteToEndOfLine' at 88;11.", repo.Uedit64.DeleteToEndOfLineInfo, new RecordItemIndex(8));
            repo.Uedit64.DeleteToEndOfLine.Click("88;11");
            Delay.Milliseconds(0);
            
            VerifydeletedToEnd();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
