///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.Editing
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NewDocumentCreatetionandotheractions recording.
    /// </summary>
    [TestModule("ed936a00-3c61-4458-b79f-d8ab8dc3079b", ModuleType.Recording, 1)]
    public partial class NewDocumentCreatetionandotheractions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static NewDocumentCreatetionandotheractions instance = new NewDocumentCreatetionandotheractions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NewDocumentCreatetionandotheractions()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NewDocumentCreatetionandotheractions Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'UltraEdit64Bit.ToolBar.Home'.", repo.UltraEdit64Bit.ToolBar.HomeInfo, new RecordItemIndex(0));
            repo.UltraEdit64Bit.ToolBar.Home.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Goto' at 22;20.", repo.UltraEdit64Bit.ToolBar.GotoInfo, new RecordItemIndex(1));
            repo.UltraEdit64Bit.ToolBar.Goto.Click("22;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.RadioButtonLineColumn' at 29;11.", repo.GoTo.RadioButtonLineColumnInfo, new RecordItemIndex(2));
            repo.GoTo.RadioButtonLineColumn.Click("29;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '14/1' with focus on 'GoTo'.", repo.GoTo.SelfInfo, new RecordItemIndex(3));
            repo.GoTo.Self.EnsureVisible();
            Keyboard.Press("14/1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.Goto' at 54;12.", repo.GoTo.GotoInfo, new RecordItemIndex(4));
            repo.GoTo.Goto.Click("54;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Goto' at 22;23.", repo.UltraEdit64Bit.ToolBar.GotoInfo, new RecordItemIndex(5));
            repo.UltraEdit64Bit.ToolBar.Goto.Click("22;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.RadioButtonLineColumn' at 45;10.", repo.GoTo.RadioButtonLineColumnInfo, new RecordItemIndex(6));
            repo.GoTo.RadioButtonLineColumn.Click("45;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '21/2' with focus on 'GoTo'.", repo.GoTo.SelfInfo, new RecordItemIndex(7));
            repo.GoTo.Self.EnsureVisible();
            Keyboard.Press("21/2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}' with focus on 'FormCUltraEditFilesUe20241025T06120'.", repo.FormCUltraEditFilesUe20241025T06120.SelfInfo, new RecordItemIndex(8));
            repo.FormCUltraEditFilesUe20241025T06120.Self.EnsureVisible();
            Keyboard.Press("{LShiftKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GoTo.Goto' at 24;11.", repo.GoTo.GotoInfo, new RecordItemIndex(9));
            repo.GoTo.Goto.Click("24;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey up}' with focus on 'FormCUltraEditFilesUe20241025T06120'.", repo.FormCUltraEditFilesUe20241025T06120.SelfInfo, new RecordItemIndex(10));
            repo.FormCUltraEditFilesUe20241025T06120.Self.EnsureVisible();
            Keyboard.Press("{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Copy' at 56;9.", repo.FormCUltraEditFilesUe20241025T06120.CopyInfo, new RecordItemIndex(11));
            repo.FormCUltraEditFilesUe20241025T06120.Copy.Click("56;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.CopySpecial' at 86;9.", repo.Uedit64.CopySpecialInfo, new RecordItemIndex(12));
            repo.Uedit64.CopySpecial.Click("86;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.CopyAsHTML' at 65;4.", repo.Uedit64.CopyAsHTMLInfo, new RecordItemIndex(13));
            repo.Uedit64.CopyAsHTML.Click("65;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.ApplicationMenu' at 20;13.", repo.Uedit64.ApplicationMenuInfo, new RecordItemIndex(14));
            repo.Uedit64.ApplicationMenu.Click("20;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.MenuItemNew' at 71;31.", repo.Uedit64.MenuItemNewInfo, new RecordItemIndex(15));
            repo.Uedit64.MenuItemNew.Click("71;31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Paste' at 21;57.", repo.Uedit64.PasteInfo, new RecordItemIndex(16));
            repo.Uedit64.Paste.Click("21;57");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Paste1' at 72;14.", repo.Uedit64.Paste1Info, new RecordItemIndex(17));
            repo.Uedit64.Paste1.Click("72;14");
            Delay.Milliseconds(0);
            
            startAndEndsWithPre();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+Home' Press with focus on 'Uedit64.FindResultsFile'.", repo.Uedit64.FindResultsFileInfo, new RecordItemIndex(19));
            Keyboard.PrepareFocus(repo.Uedit64.FindResultsFile);
            Keyboard.Press(System.Windows.Forms.Keys.Home | System.Windows.Forms.Keys.Control, 71, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}<{RShiftKey up}html' with focus on 'Uedit64'.", repo.Uedit64.SelfInfo, new RecordItemIndex(20));
            repo.Uedit64.Self.EnsureVisible();
            Keyboard.Press("{RShiftKey down}<{RShiftKey up}html");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}>{RShiftKey up}{Return}' with focus on 'Uedit64'.", repo.Uedit64.SelfInfo, new RecordItemIndex(21));
            repo.Uedit64.Self.EnsureVisible();
            Keyboard.Press("{RShiftKey down}>{RShiftKey up}{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+End' Press with focus on 'Uedit64.FindResultsFile'.", repo.Uedit64.FindResultsFileInfo, new RecordItemIndex(22));
            Keyboard.PrepareFocus(repo.Uedit64.FindResultsFile);
            Keyboard.Press(System.Windows.Forms.Keys.End | System.Windows.Forms.Keys.Control, 79, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}<{RShiftKey up}/html' with focus on 'Uedit64'.", repo.Uedit64.SelfInfo, new RecordItemIndex(23));
            repo.Uedit64.Self.EnsureVisible();
            Keyboard.Press("{RShiftKey down}<{RShiftKey up}/html");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}>{RShiftKey up}' with focus on 'Uedit64'.", repo.Uedit64.SelfInfo, new RecordItemIndex(24));
            repo.Uedit64.Self.EnsureVisible();
            Keyboard.Press("{RShiftKey down}>{RShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormEdit1UltraEdit64Bit.ApplicationMenu' at 25;13.", repo.FormEdit1UltraEdit64Bit.ApplicationMenuInfo, new RecordItemIndex(25));
            repo.FormEdit1UltraEdit64Bit.ApplicationMenu.Click("25;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.SaveAs' at 70;24.", repo.Uedit64.SaveAsInfo, new RecordItemIndex(26));
            repo.Uedit64.SaveAs.Click("70;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' JSfragment.html' with focus on 'SaveAs.Text1001'.", repo.SaveAs.Text1001Info, new RecordItemIndex(27));
            repo.SaveAs.Text1001.PressKeys(" JSfragment.html");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at 45;11.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(28));
            repo.SaveAs.ButtonSave.Click("45;11");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'Uedit64.ButtonYes' at 16;18.", repo.Uedit64.ButtonYesInfo, new RecordItemIndex(29));
                repo.Uedit64.ButtonYes.Click("16;18");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(29)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
