///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.FileHandling
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AutomaticallyDetectEncoding_IsSelected recording.
    /// </summary>
    [TestModule("875812ad-0ca5-43e5-a4bf-15077eeaaa73", ModuleType.Recording, 1)]
    public partial class AutomaticallyDetectEncoding_IsSelected : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static AutomaticallyDetectEncoding_IsSelected instance = new AutomaticallyDetectEncoding_IsSelected();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AutomaticallyDetectEncoding_IsSelected()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AutomaticallyDetectEncoding_IsSelected Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'UltraEdit64Bit.Advanced'.", repo.UltraEdit64Bit.AdvancedInfo, new RecordItemIndex(0));
            repo.UltraEdit64Bit.Advanced.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.Settings' at 8;51.", repo.UltraEdit64Bit.SettingsInfo, new RecordItemIndex(1));
            repo.UltraEdit64Bit.Settings.Click("8;51");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Configuration.FileHandling' at 59;3.", repo.Configuration.FileHandlingInfo, new RecordItemIndex(2));
            repo.Configuration.FileHandling.Click("59;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Configuration.Encoding' at 37;9.", repo.Configuration.EncodingInfo, new RecordItemIndex(3));
            repo.Configuration.Encoding.Click("37;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'Configuration.AutomaticallyDetectEncoding'.", repo.Configuration.AutomaticallyDetectEncodingInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.Configuration.AutomaticallyDetectEncodingInfo, "Checked", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Close() on item 'Configuration'.", repo.Configuration.SelfInfo, new RecordItemIndex(5));
            repo.Configuration.Self.Close();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
