///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.FileHandling
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackupFileDefaultDirectory recording.
    /// </summary>
    [TestModule("404df1b2-38d3-490c-a383-d196ede2e0c6", ModuleType.Recording, 1)]
    public partial class BackupFileDefaultDirectory : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static BackupFileDefaultDirectory instance = new BackupFileDefaultDirectory();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackupFileDefaultDirectory()
        {
            BackupDirectory = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackupFileDefaultDirectory Instance
        {
            get { return instance; }
        }

#region Variables

        string _BackupDirectory;

        /// <summary>
        /// Gets or sets the value of variable BackupDirectory.
        /// </summary>
        [TestVariable("f511f568-f93e-443a-bb6b-1d3a0959fc07")]
        public string BackupDirectory
        {
            get { return _BackupDirectory; }
            set { _BackupDirectory = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Advanced' at 28;12.", repo.Uedit64.AdvancedInfo, new RecordItemIndex(0));
            repo.Uedit64.Advanced.Click("28;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Settings' at 25;30.", repo.Uedit64.SettingsInfo, new RecordItemIndex(1));
            repo.Uedit64.Settings.Click("25;30");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Configuration.FileHandling' at 32;8.", repo.Configuration.FileHandlingInfo, new RecordItemIndex(2));
            repo.Configuration.FileHandling.Click("32;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Configuration.Backup' at 21;13.", repo.Configuration.BackupInfo, new RecordItemIndex(3));
            repo.Configuration.Backup.Click("21;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Configuration.ReplaceExtensionWithBAK' at 10;16.", repo.Configuration.ReplaceExtensionWithBAKInfo, new RecordItemIndex(4));
            repo.Configuration.ReplaceExtensionWithBAK.Click("10;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Configuration.Browse' at 21;7.", repo.Configuration.BrowseInfo, new RecordItemIndex(5));
            repo.Configuration.Browse.Click("21;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(6));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Text1152' at 81;9.", repo.Uedit64.Text1152Info, new RecordItemIndex(7));
            repo.Uedit64.Text1152.Click("81;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$BackupDirectory' with focus on 'Uedit64.Text1152'.", repo.Uedit64.Text1152Info, new RecordItemIndex(8));
            repo.Uedit64.Text1152.PressKeys(BackupDirectory);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(9));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.SelectFolder' at 42;10.", repo.Uedit64.SelectFolderInfo, new RecordItemIndex(10));
            repo.Uedit64.SelectFolder.Click("42;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(11));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'Configuration.Configuration'.", repo.Configuration.ConfigurationInfo, new RecordItemIndex(12));
            Host.Current.CloseApplication(repo.Configuration.Configuration, new Duration(0));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(13));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Edit' at 32;16.", repo.FormCUltraEditFilesUe20241025T06120.EditInfo, new RecordItemIndex(14));
            repo.FormCUltraEditFilesUe20241025T06120.Edit.Click("32;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Duplicate' at 28;39.", repo.FormCUltraEditFilesUe20241025T06120.DuplicateInfo, new RecordItemIndex(15));
            repo.FormCUltraEditFilesUe20241025T06120.Duplicate.Click("28;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(16));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.ApplicationMenu' at 21;14.", repo.Uedit64.ApplicationMenuInfo, new RecordItemIndex(17));
            repo.Uedit64.ApplicationMenu.Click("21;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Save' at 69;18.", repo.Uedit64.SaveInfo, new RecordItemIndex(18));
            repo.Uedit64.Save.Click("69;18");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
