///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.FileHandling
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CompareTheFiles recording.
    /// </summary>
    [TestModule("2b4cc9f0-17b1-4ced-9c18-59ea46d5b0ed", ModuleType.Recording, 1)]
    public partial class CompareTheFiles : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static CompareTheFiles instance = new CompareTheFiles();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CompareTheFiles()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CompareTheFiles Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'UltraEdit64Bit.Home'.", repo.UltraEdit64Bit.HomeInfo, new RecordItemIndex(0));
            repo.UltraEdit64Bit.Home.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Compare' at 16;45.", repo.FormCUltraEditFilesUe20241025T06120.CompareInfo, new RecordItemIndex(1));
            repo.FormCUltraEditFilesUe20241025T06120.Compare.Click("16;45");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'CompareFilesFolders.Compare' at 29;13.", repo.CompareFilesFolders.CompareInfo, new RecordItemIndex(2));
            repo.CompareFilesFolders.Compare.Click("29;13");
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Invoke action", "(Optional Action)\r\nInvoking Close() on item 'TrialPeriodExpiring'.", repo.TrialPeriodExpiring.SelfInfo, new RecordItemIndex(3));
                repo.TrialPeriodExpiring.Self.Close();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.TextCompareUltraCompare.Element10073, false, new RecordItemIndex(4));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.TextCompareUltraCompare.Element10074, false, new RecordItemIndex(5));
            
            Compare();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
