///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.FileHandling
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateNewFilesAndPasteTheData recording.
    /// </summary>
    [TestModule("9e7724d3-6e9a-4d38-8c63-f364dffd76fb", ModuleType.Recording, 1)]
    public partial class CreateNewFilesAndPasteTheData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static CreateNewFilesAndPasteTheData instance = new CreateNewFilesAndPasteTheData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateNewFilesAndPasteTheData()
        {
            savefilepath = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateNewFilesAndPasteTheData Instance
        {
            get { return instance; }
        }

#region Variables

        string _savefilepath;

        /// <summary>
        /// Gets or sets the value of variable savefilepath.
        /// </summary>
        [TestVariable("450c1a83-d955-4f85-9c68-402f4379bd31")]
        public string savefilepath
        {
            get { return _savefilepath; }
            set { _savefilepath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.ToolBar.Edit' at 22;10.", repo.FormCUltraEditFilesUe20241025T06120.ToolBar.EditInfo, new RecordItemIndex(0));
            repo.FormCUltraEditFilesUe20241025T06120.ToolBar.Edit.Click("22;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Select' at 24;51.", repo.FormCUltraEditFilesUe20241025T06120.SelectInfo, new RecordItemIndex(1));
            repo.FormCUltraEditFilesUe20241025T06120.Select.Click("24;51");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.SelectAll' at 38;5.", repo.Uedit64.SelectAllInfo, new RecordItemIndex(2));
            repo.Uedit64.SelectAll.Click("38;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Home' at 28;13.", repo.UltraEdit64Bit.ToolBar.HomeInfo, new RecordItemIndex(3));
            repo.UltraEdit64Bit.ToolBar.Home.Click("28;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.ToolBar.Copy' at 35;8.", repo.FormCUltraEditFilesUe20241025T06120.ToolBar.CopyInfo, new RecordItemIndex(4));
            repo.FormCUltraEditFilesUe20241025T06120.ToolBar.Copy.Click("35;8");
            Delay.Milliseconds(0);
            
            Storecontent1();
            Delay.Milliseconds(17640);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(6));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.ApplicationMenu' at 39;7.", repo.Uedit64.ApplicationMenuInfo, new RecordItemIndex(7));
            repo.Uedit64.ApplicationMenu.Click("39;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.MenuItemNew' at 60;16.", repo.Uedit64.MenuItemNewInfo, new RecordItemIndex(8));
            repo.Uedit64.MenuItemNew.Click("60;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Paste' at 17;41.", repo.Uedit64.PasteInfo, new RecordItemIndex(9));
            repo.Uedit64.Paste.Click("17;41");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Paste1' at 45;6.", repo.Uedit64.Paste1Info, new RecordItemIndex(10));
            repo.Uedit64.Paste1.Click("45;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.ApplicationMenu' at 39;7.", repo.Uedit64.ApplicationMenuInfo, new RecordItemIndex(11));
            repo.Uedit64.ApplicationMenu.Click("39;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.Save' at 47;21.", repo.Uedit64.SaveInfo, new RecordItemIndex(12));
            repo.Uedit64.Save.Click("47;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.Text1001' at 176;10.", repo.SaveAs.Text1001Info, new RecordItemIndex(13));
            repo.SaveAs.Text1001.Click("176;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SaveAs.Text1001'.", repo.SaveAs.Text1001Info, new RecordItemIndex(14));
            Keyboard.PrepareFocus(repo.SaveAs.Text1001);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+Delete' Press with focus on 'SaveAs.Text1001'.", repo.SaveAs.Text1001Info, new RecordItemIndex(15));
            Keyboard.PrepareFocus(repo.SaveAs.Text1001);
            Keyboard.Press(System.Windows.Forms.Keys.Delete | System.Windows.Forms.Keys.Control, 83, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$savefilepath' with focus on 'SaveAs.Text1001'.", repo.SaveAs.Text1001Info, new RecordItemIndex(16));
            repo.SaveAs.Text1001.PressKeys(savefilepath);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(17));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at 20;11.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(18));
            repo.SaveAs.ButtonSave.Click("20;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(19));
            Delay.Duration(300, false);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'Uedit64.ButtonYes' at 41;12.", repo.Uedit64.ButtonYesInfo, new RecordItemIndex(20));
                repo.Uedit64.ButtonYes.Click("41;12");
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(20)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
