///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Diagnostics; // For Process
using System.IO;         // For StreamWriter
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UltraEditAutomation.FileHandling
{
    public partial class CreateNewFileInCommandPrompt
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CommandPrompt()
        {
            try
            {
                // Step 1: Start Command Prompt with appropriate settings
                ProcessStartInfo processInfo = new ProcessStartInfo
                {
                    FileName = "cmd.exe", // Path to Command Prompt executable
                    Arguments = "/c uedit64 C:\\temp\\newfile.txt", // Use /c to run the command and exit
                    WorkingDirectory = @"C:\Windows\System32", // Optional starting directory
                    UseShellExecute = false,  // Allow interaction via StandardInput
                    RedirectStandardInput = true, // Redirect standard input
                    RedirectStandardOutput = true, // Capture output (optional)
                    RedirectStandardError = true, // Capture errors
                    CreateNoWindow = false // Show the Command Prompt window
                };

                // Step 2: Launch Command Prompt
                Process cmdProcess = Process.Start(processInfo);
                
                // Log success message
                Report.Info("Command Prompt opened successfully.");

                // Step 3: Wait for the process to complete
                cmdProcess.WaitForExit();

                // Log the result
                Report.Info("Command executed successfully: uedit64 C:\\temp\\newfile.txt");
            }
            catch (Exception ex)
            {
                // Log error in case of failure
                Report.Error("Error while automating Command Prompt: " + ex.Message);
            }
        }
    }
}
