///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UltraEditAutomation.FileHandling
{
    public partial class ModifyTheFile
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
       public string copiedText1;

        public void Storecontent1()
        {
           try
   			 {
           	Delay.Seconds(3);
       		 copiedText1 = System.Windows.Forms.Clipboard.GetText();
       		 Report.Info($"Captured Content1: {copiedText1}");
  			  }
   		    catch (Exception ex)
   		     {
       		 Report.Error($"Failed to capture Content1: {ex.Message}");
   			 }
        }

        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

    }
}
