///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace UltraEditAutomation.FileHandling
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateTheDataPresentInTheFile recording.
    /// </summary>
    [TestModule("44411f4e-c2d1-4eb6-a4c6-8dbb15b4ee5d", ModuleType.Recording, 1)]
    public partial class ValidateTheDataPresentInTheFile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::UltraEditAutomation.UltraEditAutomationRepository repository.
        /// </summary>
        public static global::UltraEditAutomation.UltraEditAutomationRepository repo = global::UltraEditAutomation.UltraEditAutomationRepository.Instance;

        static ValidateTheDataPresentInTheFile instance = new ValidateTheDataPresentInTheFile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateTheDataPresentInTheFile()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateTheDataPresentInTheFile Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.ToolBar.Edit' at 22;10.", repo.FormCUltraEditFilesUe20241025T06120.ToolBar.EditInfo, new RecordItemIndex(0));
            repo.FormCUltraEditFilesUe20241025T06120.ToolBar.Edit.Click("22;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.Select' at 24;51.", repo.FormCUltraEditFilesUe20241025T06120.SelectInfo, new RecordItemIndex(1));
            repo.FormCUltraEditFilesUe20241025T06120.Select.Click("24;51");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Uedit64.SelectAll' at 38;5.", repo.Uedit64.SelectAllInfo, new RecordItemIndex(2));
            repo.Uedit64.SelectAll.Click("38;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UltraEdit64Bit.ToolBar.Home' at 28;13.", repo.UltraEdit64Bit.ToolBar.HomeInfo, new RecordItemIndex(3));
            repo.UltraEdit64Bit.ToolBar.Home.Click("28;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormCUltraEditFilesUe20241025T06120.ToolBar.Copy' at 35;8.", repo.FormCUltraEditFilesUe20241025T06120.ToolBar.CopyInfo, new RecordItemIndex(4));
            repo.FormCUltraEditFilesUe20241025T06120.ToolBar.Copy.Click("35;8");
            Delay.Milliseconds(0);
            
            StoreContent2();
            Delay.Milliseconds(0);
            
            CompareContent();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
