///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace UltraEditAutomation.FileHandling
{
    public partial class VerifyThaiDetection
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ThaiLanguage()
        {
            try
            {
                // Locate the text editor element using the Ranorex Adapter
                var textEditor = Host.Local.FindSingle<Ranorex.Unknown>(repo.UltraEdit64Bit.editorScreen.GetPath());

                // Retrieve text from WindowText 
                string text = textEditor.Element.GetAttributeValueText("WindowText"); 

                // Check if the text is empty
                if (string.IsNullOrEmpty(text))
                {
                    Report.Warn("The text is empty or not accessible.");
                    return;
                }

                // Check if the text contains any Thai characters
                bool isThai = IsTextInThai(text);

                // Report the result
                if (isThai)
                {
                    Report.Info("The text contains Thai characters.");
                }
                else
                {
                    Report.Error("The text does not contain Thai characters.");
                    throw new Exception("Test case failed: The text does not contain Thai characters.");
                }
            }
            catch (RanorexException ex)
            {
                Report.Error($"Error accessing the text: {ex.Message}");
            }
        }
        
        private bool IsTextInThai(string text)
        {
            // Unicode range for Thai
            foreach (char c in text)
            {
                if (c >= 0x0E00 && c <= 0x0E7F)
                {
                    return true; // Found a Thai character
                }
            }
            return false; // No Thai characters found
        }


    }
}
