///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestSolution
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestSolutionRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c582a625-9645-499c-b837-dcf50d3cfa5e")]
    public partial class TestSolutionRepository : RepoGenBaseFolder
    {
        static TestSolutionRepository instance = new TestSolutionRepository();
        TestSolutionRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the TestSolutionRepository element repository.
        /// </summary>
        [RepositoryFolder("c582a625-9645-499c-b837-dcf50d3cfa5e")]
        public static TestSolutionRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestSolutionRepository() 
            : base("TestSolutionRepository", "/", null, 0, false, "c582a625-9645-499c-b837-dcf50d3cfa5e", ".\\RepositoryImages\\TestSolutionRepositoryc582a625.rximgres")
        {
            _calculator = new TestSolutionRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c582a625-9645-499c-b837-dcf50d3cfa5e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("5eea6e75-e384-4352-9bef-43129e9dc03b")]
        public virtual TestSolutionRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestSolutionRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("5eea6e75-e384-4352-9bef-43129e9dc03b")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            TestSolutionRepositoryFolders.NumberPadFolder _numberpad;
            TestSolutionRepositoryFolders.StandardOperatorsFolder _standardoperators;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "5eea6e75-e384-4352-9bef-43129e9dc03b", "")
            {
                _numberpad = new TestSolutionRepositoryFolders.NumberPadFolder(this);
                _standardoperators = new TestSolutionRepositoryFolders.StandardOperatorsFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5eea6e75-e384-4352-9bef-43129e9dc03b")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5eea6e75-e384-4352-9bef-43129e9dc03b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NumberPad folder.
            /// </summary>
            [RepositoryFolder("87a5b16b-3c84-4803-a825-d23ae9ea06f7")]
            public virtual TestSolutionRepositoryFolders.NumberPadFolder NumberPad
            {
                get { return _numberpad; }
            }

            /// <summary>
            /// The StandardOperators folder.
            /// </summary>
            [RepositoryFolder("23833477-e8c7-4e89-b70b-59a03b847c01")]
            public virtual TestSolutionRepositoryFolders.StandardOperatorsFolder StandardOperators
            {
                get { return _standardoperators; }
            }
        }

        /// <summary>
        /// The NumberPadFolder folder.
        /// </summary>
        [RepositoryFolder("87a5b16b-3c84-4803-a825-d23ae9ea06f7")]
        public partial class NumberPadFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num3buttonInfo;
            RepoItemInfo _num5buttonInfo;
            RepoItemInfo _num6buttonInfo;

            /// <summary>
            /// Creates a new NumberPad  folder.
            /// </summary>
            public NumberPadFolder(RepoGenBaseFolder parentFolder) :
                    base("NumberPad", ".//container[@automationid='NumberPad']", parentFolder, 30000, null, false, "87a5b16b-3c84-4803-a825-d23ae9ea06f7", "")
            {
                _num3buttonInfo = new RepoItemInfo(this, "Num3Button", "button[@automationid='num3Button']", "", 30000, null, "160b0af0-2917-4af9-a29f-a2b900f788d6");
                _num5buttonInfo = new RepoItemInfo(this, "Num5Button", "button[@automationid='num5Button']", "", 30000, null, "081eab1f-c086-4f5e-962e-664fc34de896");
                _num6buttonInfo = new RepoItemInfo(this, "Num6Button", "button[@automationid='num6Button']", "", 30000, null, "6e9af292-35cc-4801-bae2-6b8e6b5c1a14");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("87a5b16b-3c84-4803-a825-d23ae9ea06f7")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("87a5b16b-3c84-4803-a825-d23ae9ea06f7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num3Button item.
            /// </summary>
            [RepositoryItem("160b0af0-2917-4af9-a29f-a2b900f788d6")]
            public virtual Ranorex.Button Num3Button
            {
                get
                {
                    return _num3buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num3Button item info.
            /// </summary>
            [RepositoryItemInfo("160b0af0-2917-4af9-a29f-a2b900f788d6")]
            public virtual RepoItemInfo Num3ButtonInfo
            {
                get
                {
                    return _num3buttonInfo;
                }
            }

            /// <summary>
            /// The Num5Button item.
            /// </summary>
            [RepositoryItem("081eab1f-c086-4f5e-962e-664fc34de896")]
            public virtual Ranorex.Button Num5Button
            {
                get
                {
                    return _num5buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num5Button item info.
            /// </summary>
            [RepositoryItemInfo("081eab1f-c086-4f5e-962e-664fc34de896")]
            public virtual RepoItemInfo Num5ButtonInfo
            {
                get
                {
                    return _num5buttonInfo;
                }
            }

            /// <summary>
            /// The Num6Button item.
            /// </summary>
            [RepositoryItem("6e9af292-35cc-4801-bae2-6b8e6b5c1a14")]
            public virtual Ranorex.Button Num6Button
            {
                get
                {
                    return _num6buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num6Button item info.
            /// </summary>
            [RepositoryItemInfo("6e9af292-35cc-4801-bae2-6b8e6b5c1a14")]
            public virtual RepoItemInfo Num6ButtonInfo
            {
                get
                {
                    return _num6buttonInfo;
                }
            }
        }

        /// <summary>
        /// The StandardOperatorsFolder folder.
        /// </summary>
        [RepositoryFolder("23833477-e8c7-4e89-b70b-59a03b847c01")]
        public partial class StandardOperatorsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _equalbuttonInfo;
            RepoItemInfo _multiplybuttonInfo;
            RepoItemInfo _plusbuttonInfo;

            /// <summary>
            /// Creates a new StandardOperators  folder.
            /// </summary>
            public StandardOperatorsFolder(RepoGenBaseFolder parentFolder) :
                    base("StandardOperators", ".//container[@automationid='StandardOperators']", parentFolder, 30000, null, false, "23833477-e8c7-4e89-b70b-59a03b847c01", "")
            {
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", "button[@automationid='equalButton']", "", 30000, null, "2a7a53b4-872f-40f5-841f-57c571e7d96c");
                _multiplybuttonInfo = new RepoItemInfo(this, "MultiplyButton", "button[@automationid='multiplyButton']", "", 30000, null, "7ae9a933-9682-4388-86f7-9a76a746ea3c");
                _plusbuttonInfo = new RepoItemInfo(this, "PlusButton", "button[@automationid='plusButton']", "", 30000, null, "33b1f5d5-99be-498c-9c7f-4c8f16b98f50");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("23833477-e8c7-4e89-b70b-59a03b847c01")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("23833477-e8c7-4e89-b70b-59a03b847c01")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("2a7a53b4-872f-40f5-841f-57c571e7d96c")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("2a7a53b4-872f-40f5-841f-57c571e7d96c")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }

            /// <summary>
            /// The MultiplyButton item.
            /// </summary>
            [RepositoryItem("7ae9a933-9682-4388-86f7-9a76a746ea3c")]
            public virtual Ranorex.Button MultiplyButton
            {
                get
                {
                    return _multiplybuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MultiplyButton item info.
            /// </summary>
            [RepositoryItemInfo("7ae9a933-9682-4388-86f7-9a76a746ea3c")]
            public virtual RepoItemInfo MultiplyButtonInfo
            {
                get
                {
                    return _multiplybuttonInfo;
                }
            }

            /// <summary>
            /// The PlusButton item.
            /// </summary>
            [RepositoryItem("33b1f5d5-99be-498c-9c7f-4c8f16b98f50")]
            public virtual Ranorex.Button PlusButton
            {
                get
                {
                    return _plusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PlusButton item info.
            /// </summary>
            [RepositoryItemInfo("33b1f5d5-99be-498c-9c7f-4c8f16b98f50")]
            public virtual RepoItemInfo PlusButtonInfo
            {
                get
                {
                    return _plusbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
